backend:
  name: git-gateway
  repo: danielacorner/keunappa-nextjs # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  api_root: https://api.github.com # Use the GitHub API instead of GitLab's API
  token: ${{ env.GITHUB_API_TOKEN }} # Your GitHub API token
  site_domain: location.hostname
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: netlify-cms/
media_folder: public/img
public_folder: img
collections:
  - name: "items"
    label: "Items"
    folder: _items
    create: true
    fields:
      - { name: title, label: 제목, widget: string }
      - { name: primary_store_url, label: 상점 페이지 URL, widget: string }
      - {
          name: preview_image_url,
          label: 미리보기 이미지 URL,
          widget: string,
          hint: "이 항목의 미리보기 이미지로 사용됩니다.",
        }
      - {
          name: more_preview_image_urls,
          label: 더 많은 미리보기 이미지 URL,
          widget: list,
          field:
            { name: more_preview_image_url, label: Ingredient, widget: string },
          hint: "항목 세부정보 페이지에서 이 항목에 대한 추가 미리보기 이미지로 사용됩니다.",
        }
      - { name: description, label: Description, widget: markdown }
      - { name: price, label: Price, widget: number, required: false }
  - name: "collections"
    label: "컬렉션"
    folder: _collections
    create: true
    fields:
      - {
          name: title,
          label: 컬렉션 URL 제목,
          widget: string,
          hint: "이 컬렉션의 URL을 생성하는 데 사용됩니다. 고유해야 하며 공백이나 특수 문자를 포함하지 않아야 합니다.",
        }
      - {
          name: title_display,
          label: 컬렉션 표시 제목,
          widget: string,
          required: false,
          hint: "이 컬렉션의 제목으로 사용됩니다.",
        }
      - { name: description, label: 컬렉션 설명, widget: markdown }
      - {
          name: items,
          label: 수집품,
          widget: relation,
          collection: items,
          multiple: true,
          valueField: "{{slug}}",
          display_fields: ["title", "price"],
          searchFields: ["title"],
        }
      - {
          name: preview_image_url,
          label: 미리보기 이미지 URL,
          widget: string,
          hint: "이 컬렉션의 미리보기 이미지로 사용됩니다.",
          required: false,
        }
      - {
          name: order,
          label: 순서,
          widget: number,
          hint: "홈페이지에서 컬렉션을 주문하는 데 사용됩니다. 번호가 가장 낮은 컬렉션이 첫 번째가 됩니다.",
          required: false,
        }

  # add a collection with a single item "우리의 목적" which has a rich text description
  # and a single image
  - name: "purpose"
    label: "목적"
    folder: _purpose
    create: true
    fields:
      - { name: title, label: 제목, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: description, label: 설명, widget: markdown }
