backend:
  name: git-gateway
  repo: danielacorner/keunappa-nextjs # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  api_root: https://api.github.com # Use the GitHub API instead of GitLab's API
  token: ${{ env.GITHUB_API_TOKEN }} # Your GitHub API token
  # token: ${{ env.GITHUB_API_TOKEN }} # Your GitHub API token
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
