backend:
  name: git-gateway
  repo: danielacorner/keunappa-nextjs # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  api_root: https://api.github.com # Use the GitHub API instead of GitLab's API
  token: ${{ env.GITHUB_API_TOKEN }} # Your GitHub API token
  site_domain: location.hostname
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: netlify-cms/
media_folder: public/img
public_folder: img
collections:
  - name: "items"
    label: "Items"
    folder: _items
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: primary_store_url, label: URL to store page, widget: string }
      - {
          name: preview_image_url,
          label: Preview image URL,
          widget: string,
          hint: "This will be used as the preview image for this item.",
        }
      - {
          name: more_preview_image_urls,
          label: More preview image URLs,
          widget: list,
          field:
            { name: more_preview_image_url, label: Ingredient, widget: string },
          hint: "These will be used as more preview images for this item on the item details page.",
        }
      - { name: description, label: Description, widget: markdown }
      - { name: price, label: Price, widget: number, required: false }
  - name: "collections"
    label: "Collections"
    folder: _collections
    create: true
    fields:
      - {
          name: title,
          label: Collection url title,
          widget: string,
          hint: "This will be used to generate the URL for this collection. It should be unique and not contain spaces or special characters.",
        }
      - {
          name: title_display,
          label: Collection display title,
          widget: string,
          required: false,
          hint: "This will be used as the title for this collection.",
        }
      - { name: description, label: Collection Description, widget: markdown }
      - {
          name: items,
          label: Items in Collection,
          widget: relation,
          collection: items,
          multiple: true,
          valueField: "{{slug}}",
          display_fields: ["title", "price"],
          searchFields: ["title"],
        }
      - {
          name: preview_image_url,
          label: Preview image URL,
          widget: string,
          hint: "This will be used as the preview image for this collection.",
          required: false,
        }
      - {
          name: order,
          label: Order,
          widget: number,
          hint: "This will be used to order the collections on the home page. The collection with the lowest number will be first.",
          required: false,
        }
