backend:
  name: git-gateway
  repo: danielacorner/keunappa-nextjs # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  api_root: https://api.github.com # Use the GitHub API instead of GitLab's API
  token: ${{ env.GITHUB_API_TOKEN }} # Your GitHub API token
  site_domain: location.hostname
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: netlify-cms/
media_folder: public/img
public_folder: img
collections:
  - name: "items"
    label: "Items"
    folder: _items
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: number }
      - { name: url, label: URL, widget: string }
      - { name: image_url, label: Image URL, widget: string }
      - { name: description, label: Description, widget: markdown }
  - name: "pages"
    label: "Pages"
    folder: _pages
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: markdown }
      - {
          name: items,
          label: Items,
          widget: list,
          fields:
            [
              { name: title, label: Title, widget: string },
              { name: price, label: Price, widget: number },
              { name: url, label: URL, widget: string },
              { name: image_url, label: Image URL, widget: string },
              { name: description, label: Description, widget: markdown },
            ],
        }
