backend:
  name: git-gateway
  repo: danielacorner/keunappa-nextjs # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  api_root: https://api.github.com # Use the GitHub API instead of GitLab's API
  token: ${{ env.GITHUB_API_TOKEN }} # Your GitHub API token
  site_domain: location.hostname
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: netlify-cms/
media_folder: public/img
public_folder: img
collections:
  - name: "items"
    label: "Items"
    folder: _items
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: number }
      - { name: primary_store_url, label: URL to store page, widget: string }
      - { name: preview_image_url, label: Preview image URL, widget: string }
      - { name: description, label: Description, widget: markdown }
  - name: "collections"
    label: "Collections"
    folder: _collections
    create: true
    fields:
      - { name: title, label: Collection Title, widget: string }
      - { name: description, label: Collection Description, widget: markdown }
      - {
          name: items,
          label: Items in Collection,
          widget: relation,
          collection: items,
          multiple: true,
          value_field: "{{slug}}",
          display_fields: ["title", "price"],
        }
